services:
  node:
    image: node:20-alpine
    container_name: noteKitNode
    env_file:
      - ./.env
    volumes:
      - ../:/app
    working_dir: /app
    depends_on:
      - noteKitPostgres
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run migration:run && npm run seed && npm run dev"


  noteKitPostgres:
    image: postgres:17
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - noteKitDB:/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  noteKitDB: