services:
  next_js_poc_node:
    image: node:20-alpine
    container_name: nextjs
    env_file:
      - ./.env
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - next_js_poc_db
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run migration:run && npm run dev"


  next_js_poc_db:
    image: postgres:17
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - next_js_poc_db_volume:/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  next_js_poc_db_volume: