services:
  noteKitPostgres:
    image: postgres:17
    environment:
      # variables from the .env file
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_PASSWORD}
    volumes:
      - noteKitDB:/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  noteKitDB: