import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1738354549171 implements MigrationInterface {
    name = 'Migration1738354549171'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "role" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "role" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "action" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "action" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "action" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "action" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" ADD "weight" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "access_matrix" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "access_matrix" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "access_matrix" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "access_matrix" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "note" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "note" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "note" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "note" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "team" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "team" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "team_nesting" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_nesting" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_nesting" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "team_nesting" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "team_role" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_role" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_role" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "team_role" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "user_team" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_team" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_team" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "user_team" ADD "updatedById" integer`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_45c0d39d1f9ceeb56942db93cc5" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_db5173f7d27aa8a98a9fe6113df" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "FK_528f294633a808293425ae2ab56" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "FK_686b8af82beeafa884598c4da41" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "action" ADD CONSTRAINT "FK_e410a9ab25d6c066f3a72ae72c2" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "action" ADD CONSTRAINT "FK_1688a83bbeb9bcda265ff7c878f" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" ADD CONSTRAINT "FK_8de3866eb8e95d34d4e2591c870" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" ADD CONSTRAINT "FK_9ff7681554fc7725e14caf61f24" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "access_matrix" ADD CONSTRAINT "FK_1a13290922af108830818a9295b" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "access_matrix" ADD CONSTRAINT "FK_6c4ce2eecb97397c8415fdf4355" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "note" ADD CONSTRAINT "FK_1100c955b41aeaca61ddd9308d4" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "note" ADD CONSTRAINT "FK_4cb66f45783b5fa3c7f06aba3a4" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team" ADD CONSTRAINT "FK_3a93fbdeba4e1e9e47fec6bada9" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team" ADD CONSTRAINT "FK_3152d46f0ce8751aca92399783d" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_nesting" ADD CONSTRAINT "FK_cc3edb87232f54dc4e798a2481c" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_nesting" ADD CONSTRAINT "FK_60095aeab8f0da1c0f69d937b7e" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_role" ADD CONSTRAINT "FK_524ca361fbf7bb7a8d34a3b43a2" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_role" ADD CONSTRAINT "FK_b89d0ae50ec1e8c7b72b9ba4c32" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_c21047f02971482ebcce5620627" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_4ecd5f8a8ac0857ee00697b8156" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_team" ADD CONSTRAINT "FK_7896e024ffc5cb7cd5378fe54ae" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_team" ADD CONSTRAINT "FK_04f355e967ba30aab189a1ca46c" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_team" DROP CONSTRAINT "FK_04f355e967ba30aab189a1ca46c"`);
        await queryRunner.query(`ALTER TABLE "user_team" DROP CONSTRAINT "FK_7896e024ffc5cb7cd5378fe54ae"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_4ecd5f8a8ac0857ee00697b8156"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_c21047f02971482ebcce5620627"`);
        await queryRunner.query(`ALTER TABLE "team_role" DROP CONSTRAINT "FK_b89d0ae50ec1e8c7b72b9ba4c32"`);
        await queryRunner.query(`ALTER TABLE "team_role" DROP CONSTRAINT "FK_524ca361fbf7bb7a8d34a3b43a2"`);
        await queryRunner.query(`ALTER TABLE "team_nesting" DROP CONSTRAINT "FK_60095aeab8f0da1c0f69d937b7e"`);
        await queryRunner.query(`ALTER TABLE "team_nesting" DROP CONSTRAINT "FK_cc3edb87232f54dc4e798a2481c"`);
        await queryRunner.query(`ALTER TABLE "team" DROP CONSTRAINT "FK_3152d46f0ce8751aca92399783d"`);
        await queryRunner.query(`ALTER TABLE "team" DROP CONSTRAINT "FK_3a93fbdeba4e1e9e47fec6bada9"`);
        await queryRunner.query(`ALTER TABLE "note" DROP CONSTRAINT "FK_4cb66f45783b5fa3c7f06aba3a4"`);
        await queryRunner.query(`ALTER TABLE "note" DROP CONSTRAINT "FK_1100c955b41aeaca61ddd9308d4"`);
        await queryRunner.query(`ALTER TABLE "access_matrix" DROP CONSTRAINT "FK_6c4ce2eecb97397c8415fdf4355"`);
        await queryRunner.query(`ALTER TABLE "access_matrix" DROP CONSTRAINT "FK_1a13290922af108830818a9295b"`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" DROP CONSTRAINT "FK_9ff7681554fc7725e14caf61f24"`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" DROP CONSTRAINT "FK_8de3866eb8e95d34d4e2591c870"`);
        await queryRunner.query(`ALTER TABLE "action" DROP CONSTRAINT "FK_1688a83bbeb9bcda265ff7c878f"`);
        await queryRunner.query(`ALTER TABLE "action" DROP CONSTRAINT "FK_e410a9ab25d6c066f3a72ae72c2"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "FK_686b8af82beeafa884598c4da41"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "FK_528f294633a808293425ae2ab56"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_db5173f7d27aa8a98a9fe6113df"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_45c0d39d1f9ceeb56942db93cc5"`);
        await queryRunner.query(`ALTER TABLE "user_team" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "user_team" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "user_team" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user_team" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "team_role" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "team_role" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "team_role" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "team_role" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "team_nesting" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "team_nesting" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "team_nesting" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "team_nesting" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "team" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "team" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "team" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "team" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "note" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "note" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "note" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "note" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "access_matrix" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "access_matrix" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "access_matrix" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "access_matrix" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" DROP COLUMN "weight"`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "level_of_permission" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "action" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "action" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "action" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "action" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updatedById"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "createdAt"`);
    }

}
